# Generated by Django 4.2.27 on 2026-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_last_name', models.TextField()),
                ('da_first_name', models.TextField()),
                ('da_street_number', models.TextField()),
                ('da_street_name', models.TextField()),
                ('da_apt_number', models.TextField(blank=True)),
                ('da_zip_code', models.TextField()),
                ('da_dob', models.DateField()),
                ('da_date_registered', models.DateField()),
                ('da_party', models.CharField(max_length=2)),
                ('da_precinct', models.TextField()),
                ('da_v20state', models.BooleanField(default=False)),
                ('da_v21town', models.BooleanField(default=False)),
                ('da_v21primary', models.BooleanField(default=False)),
                ('da_v22general', models.BooleanField(default=False)),
                ('da_v23town', models.BooleanField(default=False)),
                ('da_voter_score', models.IntegerField()),
            ],
        ),
    ]
