# Generated by Django 4.2.27 on 2026-02-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='username',
        ),
    ]
