# Generated by Django 4.2.27 on 2026-02-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
