# Generated by Django 4.2.27 on 2026-04-28 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_the_plate', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reviewreaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
